webpack-contrib/terser-webpack-plugin

package-lock.json, package.json, src/index.js, test/__snapshots__/validation.test.js.snap
Consistent using `schema-utils` in all repos.
no
=> refactor: migrate from `@webpack-contrib/schema-utils` to `schema-utils`

.circleci/config.yml
=> ci: fix indent

package.json
=> chore: use `prepare` command

README.md
=> docs: use case insensitivity regexp

.github/ISSUE_TEMPLATE/BUG.md, .github/ISSUE_TEMPLATE/FEATURE.md, .github/ISSUE_TEMPLATE/MODIFICATION.md
fix package name in github templates
no
no
=> docs: fix package name in github templates

.eslintrc.js, .prettierrc, package-lock.json, package.json
=> chore(defaults): update

README.md, package.json, src/index.js
This PR supports the legacy Webpack 3 plugin interface, allowing this plugin to work for older versions of Webpack.
See https://github.com/webpack-contrib/terser-webpack-plugin/issues/74.
None.
=> Support legacy Webpack 3 plugin interface

README.md
=> docs: link on `terser-webpack-plugin-legacy`

src/TaskRunner.js
https://github.com/avajs/find-cache-dir#findcachediroptions
No
fixes #81
=> fix: fallback for cache directory

package-lock.json, package.json
we don't need `loader-utils` here
No
No
=> fix: removed unnecessary dependency

src/index.js
webpack exports this helper
No
No
=> refactor: do not use plugins directly

src/TaskRunner.js, test/__snapshots__/parallel-option-failure.test.js.snap, test/__snapshots__/parallel-option.test.js.snap, test/parallel-option-failure.test.js, test/parallel-option.test.js
avoid unnecessary overloading
No
Fix perf
=> fix: do not run parallel mode when you have only one file

README.md
- [*] **metadata update**
This is PR just updated the document.  No code impact.
'minimizer' only works when 'minimize = true'
=> Update document:  add 'minimize: true'

src/TaskRunner.js, src/index.js, test/cache-option.test.js
=> refactor: code

package-lock.json, package.json, src/TaskRunner.js, src/index.js, src/worker.js, test/__snapshots__/extractComments-option.test.js.snap, test/__snapshots__/parallel-option-failure.test.js.snap, test/__snapshots__/parallel-option.test.js.snap, test/__snapshots__/worker.test.js.snap, test/extractComments-option.test.js, test/parallel-option-failure.test.js, test/parallel-option.test.js, test/worker.test.js
Migrate on `jest-worker
Hope no
No
=> refactor: migrate on `jest-worker`

README.md, src/index.js, test/__snapshots__/sourceMap-option.test.js.snap, test/sourceMap-option.test.js
=> feat: respect `devtool` values for source map generation

test/__snapshots__/parallel-option-failure.test.js.snap, test/minify-option.test.js, test/parallel-option-failure.test.js
=> refactor: tests

README.md
we doesn't support webpack@3
No
No
=> docs: remove legacy link on old version of plugin

README.md
The default for the `extractComments` option changed in ad2471c4c09afe25fd3cfab2500f64588acaf0dd. This PR updates the readme to reflect that change.
=> docs: update readme to reflect new default options

CHANGELOG.md
See more in:
https://github.com/webpack-contrib/terser-webpack-plugin/issues/150
See https://github.com/webpack-contrib/terser-webpack-plugin/issues/150
No
No
=> docs: add missing breaking change for 2.0.0

package-lock.json, package.json, src/index.js, test/__snapshots__/extractComments-option.test.js.snap, test/extractComments-option.test.js
emit warning to avoid broken code for some edge cases
No
No
=> feat: emit warning when comment file conlict with an existing asset

src/index.js, test/__snapshots__/extractComments-option.test.js.snap, test/extractComments-option.test.js
fix problem with invalid url for extracted file
No
No
=> fix: correct interpretation url for extracted comment file

README.md, src/index.js, test/__snapshots__/warningsFilter-option.test.js.snap, test/warningsFilter-option.test.js
=> feat: pass asset path for warningsFilter

src/index.js, test/__snapshots__/sourceMap-option.test.js.snap, test/sourceMap-option.test.js
fixes #172
No
Need add more tests in future
=> feat: map `webpack@5` options to `terser` options

src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap
check what propagate errors from Terser
No
No
=> test: errors from `terser`

src/index.js
avoid deprecation warnings for webpack@5
No
No
=> fix: get rid deprecation warnings for `webpack@5`

src/index.js
less deprecation warnings
No
No
=> fix: get rid deprecation warnings for webpack@5

package-lock.json, package.json
=> chore(deps): update husky to the latest version

src/Webpack5Cache.js, src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack4, test/__snapshots__/TerserPlugin.test.js.snap.webpack5
Refactor + tests
No
Looks hashFunction as `Function` broken in webpack
=> refactor: code and test

.github/workflows/nodejs.yml, .prettierrc.js, README.md, babel.config.js, package-lock.json, package.json, src/index.js, test/helpers/normalizeErrors.js
Update deps
Yes
BREAKING CHANGE: minimum supported Node.js version is `10.13`
No
=> chore(deps): update

README.md, src/index.js, test/__snapshots__/extractComments-option.test.js.snap.webpack4, test/__snapshots__/extractComments-option.test.js.snap.webpack5, test/extractComments-option.test.js
override existing asset potential can break build
Yes, no we throw an error instead a warning and stop minimizing
No
=> Refactor extract comments

package-lock.json, package.json
fix security problem + fix compatibility with node@10.13 problem
No
No
=> fix: security problem

package-lock.json, src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack4, test/__snapshots__/TerserPlugin.test.js.snap.webpack5, test/warningsFilter-option.test.js
=> Fix multi compiler crash

.gitignore, package-lock.json, package.json, src/Webpack4Cache.js, src/Webpack5Cache.js, src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack5, test/__snapshots__/cache-option.test.js.snap.webpack4, test/__snapshots__/cache-option.test.js.snap.webpack5, test/__snapshots__/extractComments-option.test.js.snap.webpack5, test/__snapshots__/test-option.test.js.snap.webpack5, test/cache-option.test.js, test/helpers/getCompiler.js
avoid deprecation
In theory yes, but only for webpack@5, but because webpack@5 is in beta, you need to update webpack to latest version
fixes #284, fixes #277
=> Fix compatibility with webpack@5

package-lock.json, package.json, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack4, test/__snapshots__/TerserPlugin.test.js.snap.webpack5
=> Resolve todo with tests

src/Webpack5Cache.js, src/index.js, src/minify.js, test/worker.test.js
Avoid double compression using child compilations 
No
No
=> fix: skip double compression for child compilation

src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack4, test/__snapshots__/TerserPlugin.test.js.snap.webpack5, test/helpers/BrokenCodePlugin.js
Improve stats output for webpack@5
No
No
=> feat: show minimized assets in stats for webpack@5

README.md, package-lock.json, src/index.js, src/minify.js, test/__snapshots__/terserOptions-option.test.js.snap.webpack4, test/__snapshots__/terserOptions-option.test.js.snap.webpack5, test/__snapshots__/worker.test.js.snap.webpack4, test/__snapshots__/worker.test.js.snap.webpack5, test/terserOptions-option.test.js, test/validate-options.test.js
fixes #285
Yes, no `warnings` and `filterWarnings` anymore
No
=> Feat terser 5

src/Webpack5Cache.js, src/index.js
use new hook
No, anyway if you faces with issue feel free to open an new issue
No
=> refactor: migrate on processAssets hook

package-lock.json, package.json
update `serialize-javascript`
No
No
=> fix: security update

package-lock.json, package.json
update `serialize-javascript`
No
No
=> chore: update `serialize-javascript`

test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap.webpack5
tests, webpack@5 generate real contenthash for assets
No
No
=> test: `realContentHash`

src/index.js
=> refactor: remove unused code

test/__snapshots__/cache-option.test.js.snap.webpack4, test/__snapshots__/cache-option.test.js.snap.webpack5, test/cache-option.test.js
=> test: cache

src/index.js, test/TerserPlugin.test.js
fix related info for webpack@4
No
No
=> Fix related asset info

src/index.js, test/parallel-option.test.js
Use `worker_thread` module when it is possible (faster)
No
Only on Node.js 12 and above
=> fix: improved performance (only node@12 and above)

src/index.js, test/cache-option.test.js
Lazy worker creation
No
Need to use 10.16 and above version of Node.js for best performance
=> fix: improved performance

src/index.js
Get number of cores only once
No
No
=> fix: improve perf for watching

README.md, src/index.js, src/minify.js, test/__snapshots__/terserOptions-option.test.js.snap, test/terserOptions-option.test.js
respect `format` option + more types
No
No
=> Fix compatibility with the format option

src/index.js
=> fix: performance

src/index.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap, test/helpers/EmitNewAsset.js, test/helpers/index.js
optimize assets added lately 
Hope, no
No
=> feat: optimize JS assets added later by plugins

package.json
=> chore: fix prepare

package-lock.json, package.json, src/index.js, test/parallel-option.test.js
`jest-worker` package updated to v27
`jest-worker` package updated to v27
No
=> refactor: jest-worker package updated

README.md, package-lock.json, package.json, src/index.js, src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/__snapshots__/worker.test.js.snap, test/minify-option.test.js
allow to use `swc` as minimizer
No
Also fix types and core refactor
=> Feat swc minimizer

package-lock.json, src/index.js, test/__snapshots__/TerserPlugin.test.js.snap, test/__snapshots__/minify-option.test.js.snap, test/__snapshots__/test-option.test.js.snap, test/fixtures/entry.mjs, test/minify-option.test.js, types/index.d.ts
fix todo + fix deps + update types
No
No
=> test: fix todo

src/index.js, src/utils.js, test/TerserPlugin.test.js, test/__snapshots__/TerserPlugin.test.js.snap, test/__snapshots__/minify-option.test.js.snap, test/__snapshots__/terserOptions-option.test.js.snap, test/minify-option.test.js, types/index.d.ts
handle errors and warnings better
No
No
=> Refactor errors

package.json
fixes #437
No
/cc @gpoitch should fix the problem, wrong `types` value, can you try locally?
=> fix: types

src/index.js, types/index.d.ts
based on CI output for webpack
No
all options are optional
=> fix: types for the `extractComments` option

package.json, types/index.d.ts
fixes #443
No
Due https://github.com/microsoft/TypeScript/issues/29401
=> chore: fix scripts

package.json, scripts/fix-types.js, src/index.js, types/index.d.ts
=> Chore fix scripts

src/index.js, types/index.d.ts
=> fix: types for the `parallel` option

README.md
=> docs(readme): terser-js to terser org rename

.github/workflows/nodejs.yml, test/TerserPlugin.test.js
=> ci: add more node.js versions

package-lock.json, package.json, src/index.js, src/utils.js, types/utils.d.ts
avoid usage `p-limit` package
No
no
=> refactor: avoid usage `p-limit` package

.github/workflows/nodejs.yml
=> chore:  Update node version

src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/__snapshots__/terserOptions-option.test.js.snap, test/minify-option.test.js
fixes https://github.com/webpack-contrib/terser-webpack-plugin/issues/513
No
No
=> fix: disabled compress options for `terser` and `swc`

src/utils.js, test/__snapshots__/minify-option.test.js.snap, test/fixtures/warning.js, test/minify-option.test.js
Fixes https://github.com/webpack-contrib/terser-webpack-plugin/issues/548
No
No
=> fix: esbuild warning output

package.json, src/index.js
Similar to https://github.com/webpack-contrib/compression-webpack-plugin/pull/373
Related to https://github.com/webpack/webpack/pull/17659.
No
Compatibility for Node.js@18 and allow to reuse `require("crypto").createHash` if webpack is lower then https://github.com/webpack/webpack/pull/17628
=> fix: compatibility with Node.js@18

src/index.js, src/utils.js, types/index.d.ts, types/utils.d.ts
=> fix: `ecma` and `module` types in minimizer options

.cspell.json, .github/workflows/nodejs.yml
=> ci: add node v24
