README.md, src/options.json, test/__snapshots__/validation.test.js.snap, test/validation.test.js
=> feat: full coverage schema options validation

src/index.js
In webpack@5, `chunks` is a `Set` and thus should be converted to an array.
n/a
This change makes the plugin compatible with webpack 4 and 5.
=> fix(index): handle `chunks` provided as a `{Set}`

README.md, src/index.js, src/options.json, test/__snapshots__/chunkFilter-option.test.js.snap, test/__snapshots__/validation.test.js.snap, test/chunkFilter-option.test.js, test/validation.test.js
Allowing to filter `chunks`.
No
No
=> feat: `chunkFilter` option for filtering chunks

src/minify.js
fixes #66, #67 
Named imports have better interoperability than default imports and it is applicable to all versions of terser.
=> fix: use named imports for terser.minify

package-lock.json, package.json, src/TaskRunner.js
fixes #21 
No
https://github.com/webpack-contrib/terser-webpack-plugin/issues/89
=> fix: disable parallel on WSL due bugs

package.json, src/index.js, src/minify.js, test/__snapshots__/sourceMap-option.test.js.snap, test/__snapshots__/worker.test.js.snap, test/sourceMap-option.test.js
fixes https://github.com/webpack/webpack/issues/8302
Mappings generated when combining bundle source map with terser source map are not very fine, which leads to validation errors and low quality source maps.
There are many causes:
* webpack generates mappings that map a line to a line
* The SourceMap spec has no idea of: "this is a copied line"
We had a similar problem with webpack replacements (using the `ReplaceSource` from webpack-sources) and a good fix turned out to be:
Assume that mappings, where generates source and original source are identical for a mapping, map source code char by char.
With this assumption mappings don't have to be super exact as long code stays equal. This allows to apply the high quality terser SourceMap to the lower quality webpack …
=> generate higher quality SourceMaps

src/minify.js, test/__snapshots__/extractComments-option.test.js.snap, test/extractComments-option.test.js
fixes #20
Yes
BREAKING CHANGE: using the `extractComments.condition` option with `true` value extract only `some` comments
No
=> fix: make `extractComments` API more consistent

package-lock.json, package.json, src/TaskRunner.js
Always use `parallel` including WSL
No, should be fix
Need WSL CI
=> fix: parallel on wsl

README.md, test/__snapshots__/sourceMap-option.test.js.snap, test/sourceMap-option.test.js
=> docs: issue-83

src/TaskRunner.js, src/index.js
Reduce memory usage when no files for uglify
No
No
=> fix: reduce memory usage

src/TaskRunner.js, src/index.js, test/parallel-option.test.js
Revert, this often leads to memory overflow, so it is best to always use an external process
No
No
=> fix: revert do not run parallel mode when you have only one file

README.md, src/index.js, test/__snapshots__/extractComments-option.test.js.snap.webpack4, test/__snapshots__/extractComments-option.test.js.snap.webpack5, test/__snapshots__/terserOptions-option.test.js.snap.webpack4, test/__snapshots__/terserOptions-option.test.js.snap.webpack5, test/extractComments-option.test.js
Let me refer you to a twitter thread with @sokra 😄 
https://twitter.com/wSokra/status/1220069497660411904
> Send a PR to change the name to .LICENSE.txt by default.
n/a
=> fix: license files now have .txt suffix by default

README.md
This PR updates README and provides information how to fix `Error: Call retries were exceeded` error on environments that doesn't provide real available count of CPUs.
**Related issues:**
- https://github.com/webpack-contrib/terser-webpack-plugin/issues/143
- fixes #202
N/A
=> docs(readme): update `parallel` option and explain fix for circleci

README.md, src/index.js, test/warningsFilter-option.test.js
Better order of arguments
Yes
BREAKING CHANGE: change arguments order for the `warningFilter` option from `Function<(warning, file, source) -> Boolean>` to `Function<(file, warning, source) -> Boolean>`
No
=> refactor: `warningsFilter` option

src/index.js
If plugin uses minimize options from `compiler.optimization`, it will fail because of default terser plugin options object. Field `chunkFilter` is not allowed, but it contains in default options object.
Example: https://github.com/NekR/offline-plugin/blob/66cde2c7784b5be8c84fecbb93c6f9f96faacdb5/src/service-worker.js#L106
As i see, `chunkFilter` never uses in plugin, so it can be removed easily.
Minimal repo to reproduce:
https://github.com/Dekkee/terser-bug
no breaking changes according to 3.0.0 release
=> Remove redundant chunkFilter

README.md, src/minify.js, test/__snapshots__/minify-option.test.js.snap.webpack4, test/__snapshots__/minify-option.test.js.snap.webpack5, test/minify-option.test.js
allow to use `terserOptions` for custom minimizers
No
I will put `esbuild` example in near future
=> feat: pass the `terserOptions` to the `minify` option

package-lock.json, package.json
Since 1.2.4 `terser-webpack-plugin-legacy` depends on `core-js@2`.
The purpose of this PR is prevent potential breaking change for `terser-webpack-plugin-legacy` users that don't have `core-js@2`.
=> chore: [terser-webpack-plugin-legacy] add core-js@2 to dependencies

package-lock.json, package.json, src/index.js, test/TerserPlugin.test.js
remove old code + fix depredations in tests
No
No
=> refactor: code

README.md
Some people still install and set up this plugin in their webpack explicitly. The proposed line in the readme is supposed to make it easier for the newcomers.
none
=> No need to install it if you use webpack v4+

src/index.js
This simply removes a debug log that crept in here: https://github.com/webpack-contrib/terser-webpack-plugin/pull/373/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R214
None
=> chore: remove verbose debug log

README.md
Many peoples seems upset because they failed to install this lib with webpack 4: https://github.com/webpack-contrib/terser-webpack-plugin/issues/335#issuecomment-709997726. Since "Webpack v5 comes with the latest terser-webpack-plugin out of the box", **the only users that want to install it manually would be the one that use v4**. I guess people would be more happy with this hint.
Scenario: I did not know terser and had to improve a webpack (v4) config file. I read that I have to replace uglify plugin which is not maintained with terser. So I went to this repo and copy/pasted the install line as stated in the readme. It failed.
Feel free to ask me anything, I would be super happy to improve my PR!
=> doc: webpack v4 needs terser v4

README.md, src/index.js, src/minify.js, src/utils.js, types/index.d.ts, types/minify.d.ts, types/utils.d.ts
fixes #439
Potential yes, because some types were removed, but they were removed due invalid usage of optional peer dependencies, to fix it we should ast developers provide options for usage , here updated examples https://github.com/webpack-contrib/terser-webpack-plugin#typescript
No
=> Refactor types

package-lock.json, package.json, src/cjs.js, src/index.js, src/minify.js, src/utils.js, test/cjs.test.js, types/cjs.d.ts, types/index.d.ts
removed cjs wrapper and generated types in commonjs format (`export =` and `namespaces` used in types), now you can directly use exported types
Potentially yes, but we use `babel` and our code in commonjs format, but typescript generate ESM format for declarations, it is bug
No
=> feat: remove cjs wrapper and improve types format

README.md, package-lock.json, package.json, src/index.js, src/utils.js, test/TerserPlugin.test.js, types/index.d.ts, types/utils.d.ts
The trace-mapping module is faster than source-map in every benchmark
https://github.com/jridgewell/trace-mapping#benchmarks
It's also being adopted by many packages across the ecosystem ([Jest](https://github.com/facebook/jest/pull/12692), [Babel](https://github.com/babel/babel/blob/main/CHANGELOG.md#v71710-2022-04-29), [Terser](https://github.com/terser/terser/blob/master/CHANGELOG.md#v5140) at least have included it already)
And it doesn't need to be async like `source-map` 0.7.*
A previous PR to upgrade for `source-map` 0.7 was refused in the past : https://github.com/webpack-contrib/terser-webpack-plugin/pull/280
None
=> perf: replace source-map package with @jridgewell/trace-mapping

src/utils.js, types/utils.d.ts
fixes https://github.com/webpack-contrib/terser-webpack-plugin/issues/511
No
No
=> fix: types

package-lock.json, package.json
Playing dependency wack a mole with a few upstream packages - https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607
Build and tests all pass.  Changes between 6.0.1 and 6.0.1 are minimal.
=> build(dep): update serialize-javascript to 6.0.2

src/index.js, src/utils.js, types/index.d.ts, types/utils.d.ts
Worker threads are actually problematic for SWC/esbuild because of thread locals.
Closes #580
Replaces #616
=> fix(swc/esbuild): allows minifiers to set worker thread support

README.md, src/index.js, test/__snapshots__/parallel-option.test.js.snap, test/parallel-option.test.js
…able
Use `os.availableParallelism()` when it is available 
No
No
=> fix: use `os.availableParallelism()` for parallelism when it is available
